services:
  rust:
    build: .
    container_name: rust
    volumes:
      - ./files:/home/rust
    ports:
      - 8080:8000
    tty: true
    stdin_open: true
   
  python:
    image: python:3.9-slim-buster
    container_name: python
    volumes:
      - ./files:/app
    environment:
      - "CUDA_VERSION=10.2"
    command:  bash -c "apt-get update && apt-get install -y --no-install-recommends cuda-libraries-$CUDA_VERSION cuda-cudart-$CUDA_VERSION
