FROM rust:latest

# Install the required dependencies
RUN apt-get update && apt-get install -y \
    clang \
    cmake \
    pkg-config 

ENV PYTHON_VERSION=${PYTHON_VERSION}
ENV NODE_VERSION=14


RUN apt-get update && apt-get install -y \
    curl \
    git \
    build-essential \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    wget \
    curl \
    llvm \
    libncurses5-dev \
    libncursesw5-dev \
    xz-utils \
    tk-dev

RUN git clone https://github.com/pyenv/pyenv.git ~/.pyenv
ENV PATH "$PATH:~/.pyenv/bin"
RUN echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
RUN echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
RUN echo 'eval "$(pyenv init -)"' >> ~/.bashrc

RUN . ~/.bashrc && pyenv install ${PYTHON_VERSION}
RUN . ~/.bashrc && pyenv global ${PYTHON_VERSION}

# Install nvm
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash

# Install the specified version of Node.js
RUN . ~/.nvm/nvm.sh && nvm install ${NODE_VERSION}


# Expose the port that the application will run on
EXPOSE 8000


# Create a new user and set the working directory
# RUN useradd -m rust
# USER rust
# WORKDIR /home/rust