version: "3.8"

services:
  rust:
    build: .
    container_name: rust
    volumes:
      - ./code:/home/rust
    ports:
      - "2222:22"
    tty: true
    stdin_open: true
    command: /usr/sbin/sshd -D