services:
  rust:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: rust
    volumes:
      - ./files:/home/rust
    ports:
      - 8080:8000
    tty: true
    stdin_open: true
