FROM nvidia/cuda:10.1-runtime

# Install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# Set the PATH to include Rust's bin directory
ENV PATH="/root/.cargo/bin:${PATH}"

# Install the necessary dependencies for CUDA
RUN apt-get update && apt-get install -y --no-install-recommends \
    cuda-libraries-10-1 \
    cuda-nvml-dev-10-1 \
    cuda-minimal-build-10-1 \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set the LD_LIBRARY_PATH to include CUDA's lib64 directory
ENV LD_LIBRARY_PATH="/usr/local/cuda/lib64:${LD_LIBRARY_PATH}"