version: '3'
services:
  rust-cuda:
    build:
      context: .
      dockerfile: Dockerfile
    image: myimage
    container_name: rust-cuda
    volumes:
      - ./files:/app
    ports:
      - "8080:8080"
    command: "cargo run --release --bin webserver"