FROM rust:latest

# Install the required dependencies
RUN apt-get update && apt-get install -y \
    clang \
    cmake \
    pkg-config 

ENV PYTHON_VERSION=${PYTHON_VERSION}


RUN apt-get update && apt-get install -y python${PYTHON_VERSION} python${PYTHON_VERSION}-dev python3-pip nano 


# Expose the port that the application will run on
EXPOSE 8000


# Create a new user and set the working directory
# RUN useradd -m rust
# USER rust
# WORKDIR /home/rust