version: "3"
services:
  rust:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust
    volumes:
      - ./files:/home/rust
    ports:
      - 8181:8000
      
    tty: true
    stdin_open: true

    environment:
      - PYTHON_VERSION=3.9
      - NODE_VERSION=14
